### ISSUE TITLE
Using Input component throws error relating to color function.

### ISSUE THREAD

**Issue by craigthomasfrost** [pusher/pusher-ui#29]
When attempting to use `Input` in the Mimir project, the app throws an error:

> Passed an incorrect argument to a color function, please pass a string representation of a color.

Looks as though it's caused by the `transparentize` function from Polished. We ran into the same issue in the previous implementation of pusher-ui. Resolution, IIRC, was to resolve the color to a string _before_ using it within the `transparentize` function.

**Comment by hph** [comment]
I think we can set defaultProps?
